<?php

use App\Http\Controllers\Api\AdministradorController;
use App\Http\Controllers\Api\AluguelController;
use App\Http\Controllers\Api\AtendenteController;
use App\Http\Controllers\Api\BairroController;
use App\Http\Controllers\Api\CepController;
use App\Http\Controllers\Api\CidadeController;
use App\Http\Controllers\Api\CnhController;
use App\Http\Controllers\Api\ContratoFrotaController;
use App\Http\Controllers\Api\EmpresaController;
use App\Http\Controllers\Api\EstadoController;
use App\Http\Controllers\Api\FilialEnderecoController;
use App\Http\Controllers\Api\FilialController;
use App\Http\Controllers\Api\FuncionarioController;
use App\Http\Controllers\Api\GerenteComercialController;
use App\Http\Controllers\Api\LogradouroController;
use App\Http\Controllers\Api\LoteController;
use App\Http\Controllers\Api\MontadoraEnderecoController;
use App\Http\Controllers\Api\MontadoraController;
use App\Http\Controllers\Api\OficinaEnderecoController;
use App\Http\Controllers\Api\OficinaController;
use App\Http\Controllers\Api\PessoaFisicaController;
use App\Http\Controllers\Api\ServicoController;
use App\Http\Controllers\Api\UsuarioEnderecoController;
use App\Http\Controllers\Api\UsuarioController;
use App\Http\Controllers\Api\VeiculoController;
use App\Http\Controllers\Api\VendaController;
use Illuminate\Support\Facades\Route;

// Listagem de rotas de API para os recursos do sistema
Route::apiResource('filiais', FilialController::class);
Route::apiResource('montadoras', MontadoraController::class);
Route::apiResource('oficinas', OficinaController::class);
Route::apiResource('usuarios', UsuarioController::class);
Route::apiResource('funcionarios', FuncionarioController::class);
Route::apiResource('gerentes-comerciais', GerenteComercialController::class);
Route::apiResource('administradores', AdministradorController::class);
Route::apiResource('atendentes', AtendenteController::class);
Route::apiResource('lotes', LoteController::class);
Route::apiResource('veiculos', VeiculoController::class);
Route::apiResource('cnhs', CnhController::class);
Route::apiResource('pessoas-fisicas', PessoaFisicaController::class);
Route::apiResource('empresas', EmpresaController::class);
Route::apiResource('contratos-frota', ContratoFrotaController::class);
Route::apiResource('servicos', ServicoController::class);
Route::patch('alugueis/{id}/devolver', [AluguelController::class, 'devolver']);
Route::apiResource('alugueis', AluguelController::class);
Route::apiResource('vendas', VendaController::class);
Route::apiResource('estados', EstadoController::class);
Route::apiResource('cidades', CidadeController::class);
Route::apiResource('bairros', BairroController::class);
Route::apiResource('logradouros', LogradouroController::class);
Route::apiResource('ceps', CepController::class);
Route::apiResource('usuarios-enderecos', UsuarioEnderecoController::class);
Route::apiResource('oficinas-enderecos', OficinaEnderecoController::class);
Route::apiResource('montadoras-enderecos', MontadoraEnderecoController::class);
Route::apiResource('filiais-enderecos', FilialEnderecoController::class);
